services:
  pgdatabase:
    image: postgres:12
    container_name: pgdatabase
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trip_data
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - pgnetwork
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - pgnetwork

networks:
  pgnetwork: